### ISSUE TITLE
The online installation cluster storage configuration cannot be switched

### ISSUE THREAD

**Issue by sacredartr** [kubeclipper-labs/console#1]
**Describe the Bug**
  Online installation of cluster storage configuration cannot be switched

**Versions Used**
Kubernetes: master branch
Kubeclipper: master branch

**Environment**
CentOS 7.7.1908
masters:  4cpu/16g; 
3 nodes: 4cpu/16g
3 nodes: 4cpu/12g

**How To Reproduce**
    
<img width="1194" alt="install" src="https://user-images.githubusercontent.com/56632872/179145824-fc73fb69-6e21-422a-911b-696cff0be446.png">

**Expected behavior**
  Online installation of cluster storage configuration can be switched

**Comment by x893675** [comment]
/kind need-verify
@sacredartr

**Comment by x893675** [comment]
test successful.
fixed
/close
