### ISSUE TITLE
When copying and filling in the address of the image warehouse installed online, the containerd image warehouse is not automatically supplemented

### ISSUE THREAD

**Issue by lysign** [kubeclipper-labs/console#14]
**Describe the Bug**
When copying and filling in the address of the image warehouse installed online, the containerd image warehouse is not automatically supplemented

**Versions Used**
Kubernetes:
Kubeclipper:

**Environment**

**How To Reproduce**
![image](https://user-images.githubusercontent.com/32431848/180754574-d358eadf-9d3b-4170-85c0-ebd803488b56.png)

**Expected behavior**
When the address of the image warehouse installed online is copied and filled in, the containerd image warehouse will be automatically supplemented

**Comment by x893675** [comment]
has beed fixed
/close

**Comment by x893675** [comment]
/kind need-to-test
@Mengchenchen @sacredartr
/remove-kind need-verify
