### ISSUE TITLE
The storage item added to cluster cannot be configured

### ISSUE THREAD

**Issue by sacredartr** [kubeclipper-labs/console#64]
**Describe the Bug**
the storage item added to cluster cannot be configured

**Versions Used**
Kubernetes: v1.1.0
Kubeclipper: v1.1.0

**Environment**
How many nodes and their hardware configuration:

CentOS 7.7.1908
masters: 4cpu/8g

**How To Reproduce**
1. Go to 'Cluster Manager - Cluster'
2. Click on 'Add Storage'
3. Jump to 'Adding Storage Setting'
4. Can not edit setting

** Screenshot**
<img width="1397" alt="企业微信截图_9123b3c7-04e1-4030-9e37-fefdd1a3938a" src="https://user-images.githubusercontent.com/56632872/183610377-d2777d39-c504-45c1-8e33-354ce49ca102.png">

**Comment by x893675** [comment]
fixed in pr#71, now closed
/closed
