### ISSUE TITLE
The nfs templates cannot be used when creating a cluster

### ISSUE THREAD

**Issue by sacredartr** [kubeclipper-labs/console#66]
**Describe the Bug**
The nfs templates cannot be used when creating a cluster

**Versions Used**
Kubernetes: v1.1.0
Kubeclipper: v1.1.0

**Environment**
How many nodes and their hardware configuration:

CentOS 7.7.1908
masters: 4cpu/8g

**How To Reproduce**
1. Go to 'Cluster Manager - Cluster'
2. Click on 'Create Cluster' and select offline image
3. Jump to 'Storage Config'
4. Can not select nfs templates

**Screenshot**
<img width="1246" alt="截屏2022-08-09 17 13 59" src="https://user-images.githubusercontent.com/56632872/183613448-db0a1602-18f4-4873-af49-3c7bc3d4445c.png">
<img width="1075" alt="截屏2022-08-09 17 13 50" src="https://user-images.githubusercontent.com/56632872/183613477-1f50da1c-3984-47da-8e89-07ae0f84def6.png">

**Comment by x893675** [comment]
fixed in https://github.com/kubeclipper-labs/console/pull/71

/close
