### ISSUE TITLE
Install plugins page individually is blank

### ISSUE THREAD

**Issue by Mengchenchen** [kubeclipper-labs/console#72]
**Describe the Bug**
Install plugins page individually is blank 

![下拉](https://user-images.githubusercontent.com/100403985/183873340-600df80c-a91a-40e1-9183-916e501f9303.png)

![存储项](https://user-images.githubusercontent.com/100403985/183873373-64d338fa-ba67-4220-bf71-22ca1ed99776.png)

**Comment by x893675** [comment]
duplicate with https://github.com/kubeclipper-labs/console/issues/64
fixed
/close

**Comment by x893675** [comment]
/kind need-to-test 
@Mengchenchen @sacredartr
