### ISSUE TITLE
No login log is generated after login with oauth

### ISSUE THREAD

**Issue by Mengchenchen** [kubeclipper-labs/console#81]
**Describe the Bug**
No login log is generated after loggin with oauth

![oauth](https://user-images.githubusercontent.com/100403985/184089243-a35a9788-a433-482f-afc9-0b9de567aad9.png)

![login](https://user-images.githubusercontent.com/100403985/184089375-91b7be94-9e50-489e-af9a-df3e262361a4.png)

**Comment by x893675** [comment]
backend  issue: https://github.com/kubeclipper-labs/kubeclipper/issues/97

/close
