### ISSUE TITLE
After the login expires, the oauth login entry will disappear

### ISSUE THREAD

**Issue by Mengchenchen** [kubeclipper-labs/console#85]
**Describe the Bug**
After the login expires, the oauth login entry will disappear

![login](https://user-images.githubusercontent.com/100403985/184268413-5fc7043e-2c03-4509-9f5f-a8a0222180e2.png)

<img width="727" alt="peizhi" src="https://user-images.githubusercontent.com/100403985/184268810-cd7a9429-bb4e-4ecc-bfeb-aa5865636118.png">

After logging in with admin, it will reappear after logging out

**Comment by lysign** [comment]
kind/need-to-test
